version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    container_name: SQLServer
    restart: on-failure
    ports:
      - '1433:1433'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Python.123456'
      MSSQL_PID: 'Express'
