version: '3'

services:
  db:
    image: postgres:16.2
    container_name: PostgreSQL
    restart: on-failure
    ports:
      - '5432:5432'

    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: database_name
