services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: SQLServer
    restart: on-failure
    ports:
      - '1433:1433'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Docker.123456'
      MSSQL_PID: 'Developer'
      # MSSQL_PID: 'Express'
