version: "3"

services:
  db:
    image: mariadb:11.4.1-rc-jammy
    container_name: MariaDB
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: database_name
