services:
  db:
    image: mysql:8.4.0
    # image: mysql:5.7.44
    container_name: MySQL
    restart: on-failure
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: database_name
