version: "3"

services:
  db:
    image: mariadb:10.5.4-focal
    container_name: MariaDB
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - mariadb-data:/var/lib/mysql
      # - ./data/db:/var/lib/mysql
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: database_name
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"

# volumes:
#   mariadb-data:
